Repository RedHatInsights/insights-dashboard, pull requests merged in 2020-04, with the labels that each got.

#87 Update template for system inventory card
  build/messages/src/Messages.json
  locales/data.json
  locales/translations.json
  src/Icons/CriticalIcon.js
  src/Icons/FinishedIcon.js
  src/Icons/Icons.scss
  src/Icons/InfoIcon.js
  src/Icons/RunningIcon.js
  src/Icons/WarningIcon.js
  src/Messages.js
  src/PresentationalComponents/Dashboard/Dashboard.js
  src/PresentationalComponents/DeniedState/DeniedState.js
  src/PresentationalComponents/IconInline/IconInline.js
  src/PresentationalComponents/IconInline/IconInline.scss
  src/PresentationalComponents/InfoInline/InfoInline.js
  src/PresentationalComponents/NumberData/NumberData.js
  src/PresentationalComponents/NumberData/NumberData.scss
  src/PresentationalComponents/NumberDescription/NumberDescription.js
  src/PresentationalComponents/NumberDescription/NumberDescription.scss
  src/PresentationalComponents/Template/TemplateCard.js
  src/SmartComponents/Advisor/Advisor.js
  src/SmartComponents/Compliance/ComplianceCard.js
  src/SmartComponents/PatchManager/PatchManagerCard.js
  src/SmartComponents/Remediations/RemediationsCard.js
  src/SmartComponents/SubscriptionsUtilized/SubscriptionsUtilizedCard.js
  src/SmartComponents/SystemInventory/SystemInventoryCard.js
  src/SmartComponents/Vulnerability/VulnerabilityCard.js
Labels: bug

#92 Cull, organize, bump package.json for primetime
  package-lock.json
  package.json
Labels: enhancement

#89 Remove custom policies / clean up styles based on feedback from design
  build/messages/src/Messages.json
  locales/data.json
  locales/translations.json
  src/ChartTemplates/PieChart/PieChartTemplate.js
  src/ChartTemplates/PieChart/PieChartTemplate.scss
  src/ChartTemplates/StackChart/_StackChartTemplate.scss
  src/Messages.js
  src/PresentationalComponents/Dashboard/Dashboard.js
  src/PresentationalComponents/Dashboard/_dashboard.scss
  src/SmartComponents/Advisor/Advisor.js
  src/SmartComponents/Compliance/ComplianceCard.js
  src/SmartComponents/Compliance/ComplianceCard.scss
  src/SmartComponents/CustomPolicies/CustomPoliciesCard.js
  src/SmartComponents/CustomPolicies/CustomPoliciesCard.scss
  src/SmartComponents/PatchManager/PatchManagerCard.js
  src/SmartComponents/PatchManager/PatchManagerCard.scss
  src/SmartComponents/Remediations/RemediationsCard.js
  src/SmartComponents/Remediations/RemediationsCard.scss
  src/SmartComponents/Vulnerability/VulnerabilityCard.js
Labels: bug, enhancement

#101 Remediation card isn't ready, lets hide it, auto arrange imports
  src/PresentationalComponents/Dashboard/Dashboard.js
Labels: bug

#100 fix(vulnerability card): Add cvss score links
  src/SmartComponents/Vulnerability/Constants.js
  src/SmartComponents/Vulnerability/VulnerabilityCard.js
Labels: bug

#103 Compliance score is out of 100, not 1
  src/SmartComponents/Compliance/ComplianceCard.js
Labels: bug

#104 fix esi tag
  src/index.html
Labels: bug

#105 add check for org admin
  src/App.js
  src/PresentationalComponents/Dashboard/Dashboard.js
Labels: bug

#106 fix compliance card
  src/SmartComponents/Compliance/ComplianceCard.js
Labels: bug

#107 Culls advisor incident call params
  src/AppConstants.js
Labels: bug

#109 fix subscriptions utilized card, sockets vs cores display
  build/messages/src/Messages.json
  src/Messages.js
  src/SmartComponents/SubscriptionsUtilized/SubscriptionsUtilizedCard.js
  src/SmartComponents/SubscriptionsUtilized/SubscriptionsUtilizedHelpers.js
  src/SmartComponents/SubscriptionsUtilized/SubscriptionsUtilizedHelpers.test.js
  src/SmartComponents/SubscriptionsUtilized/__snapshots__/SubscriptionsUtilizedHelpers.test.js.snap
Labels: bug

#111 remove max height from first card group
  src/PresentationalComponents/Dashboard/_dashboard.scss
Labels: bug

#112 Remediations card
  build/messages/src/Messages.json
  package-lock.json
  package.json
  src/AppActions.js
  src/AppConstants.js
  src/AppReducer.js
  src/Icons/QuestionIcon.js
  src/Messages.js
  src/PresentationalComponents/Dashboard/Dashboard.js
  src/SmartComponents/Remediations/RemediationsCard.js
  src/SmartComponents/Remediations/RemediationsCard.scss
  src/SmartComponents/Remediations/RemediationsEmptyState.js
  src/SmartComponents/Remediations/RemediationsEmptyState.scss
  src/SmartComponents/Remediations/RunStatus.js
  src/SmartComponents/Remediations/RunStatus.scss
Labels: enhancement

#115 Inventory card
  build/messages/src/Messages.json
  src/AppActions.js
  src/AppConstants.js
  src/AppReducer.js
  src/Messages.js
  src/PresentationalComponents/IconInline/IconInline.js
  src/SmartComponents/SystemInventory/SystemInventoryCard.js
Labels: enhancement

#117 remove download report from compliance
  src/SmartComponents/Compliance/ComplianceCard.js
  src/SmartComponents/Compliance/ComplianceCard.scss
Labels: bug

#121 ignore messages
  .gitignore
Labels: enhancement

#118 vulnerabilities to vulnerability
  build/messages/src/Messages.json
  src/Messages.js
Labels: bug

#123 Add failure state
  build/messages/src/Messages.json
  src/Messages.js
  src/PresentationalComponents/FailState/FailState.js
  src/SmartComponents/Advisor/Advisor.js
  src/SmartComponents/Compliance/ComplianceCard.js
  src/SmartComponents/PatchManager/PatchManagerCard.js
  src/SmartComponents/Remediations/RemediationsCard.js
  src/SmartComponents/SystemInventory/SystemInventoryCard.js
  src/SmartComponents/Vulnerability/VulnerabilityCard.js
Labels: enhancement

#125 All these different apis have different error response formats
  src/Store/index.js
Labels: bug

#124 Followup to #123, DRY's out advisor failed state a lil bit
  src/SmartComponents/Advisor/Advisor.js
Labels: bug

#127 Change title
  build/messages/src/Messages.json
  locales/data.json
  locales/translations.json
  src/Messages.js
Labels: enhancement

#128 Updates deps, cleans up a few depreciated files
  package-lock.json
  package.json
  src/Store/index.js
  src/Utilities/ReducerRegistry.js
  src/Utilities/skeletonAsyncCard.js
Labels: bug

#126 fix subscriptions utilized card, apply error logic for user opt-in
  build/messages/src/Messages.json
  src/AppReducer.js
  src/Messages.js
  src/SmartComponents/SubscriptionsUtilized/SubscriptionsUtilizedCard.js
  src/SmartComponents/SubscriptionsUtilized/SubscriptionsUtilizedCard.scss
Labels: bug

#129 update empty state on top to use small text
  src/PresentationalComponents/FailState/FailState.js
  src/PresentationalComponents/FailState/FailState.scss
  src/SmartComponents/PatchManager/PatchManagerCard.js
  src/SmartComponents/SubscriptionsUtilized/SubscriptionsUtilizedCard.js
  src/SmartComponents/SystemInventory/SystemInventoryCard.js
Labels: bug

#116 allow subs watch to everyone
  src/App.js
Labels: enhancement

#131 add state for no systems
  build/messages/src/Messages.json
  src/App.js
  src/Messages.js
  src/PresentationalComponents/Dashboard/Dashboard.js
  src/PresentationalComponents/NoSystems/NoSystems.js
  src/PresentationalComponents/NoSystems/NoSystems.scss
Labels: enhancement

#133 Update all non-breaking deps, remove some unnecessary ones
  package-lock.json
  package.json
Labels: enhancement

#132 add tooltip to inventory info icon
  build/messages/src/Messages.json
  src/Messages.js
  src/PresentationalComponents/NumberData/NumberData.js
  src/PresentationalComponents/NumberDescription/NumberDescription.js
  src/SmartComponents/SystemInventory/SystemInventoryCard.js
  src/SmartComponents/SystemInventory/SystemInventoryCard.scss
Labels: enhancement

#135 remove lock icon from permission state
  src/PresentationalComponents/DeniedState/DeniedState.js
Labels: bug

#136 Fix responsiveness of stack charts
  src/ChartTemplates/StackChart/StackChartTemplate.js
  src/ChartTemplates/StackChart/_StackChartTemplate.scss
  src/PresentationalComponents/Dashboard/_dashboard.scss
Labels: enhancement

#138 fix subscriptions utilized card, apply no data available
  build/messages/src/Messages.json
  src/Messages.js
  src/SmartComponents/SubscriptionsUtilized/SubscriptionsUtilizedCard.js
  src/SmartComponents/SubscriptionsUtilized/SubscriptionsUtilizedHelpers.test.js
  src/SmartComponents/SubscriptionsUtilized/__snapshots__/SubscriptionsUtilizedHelpers.test.js.snap
Labels: bug

#139 remove notifications portal
  package-lock.json
  package.json
  src/Store/index.js
  src/entry-dev.js
  src/entry.js
Labels: enhancement

#141 fix subscriptions utilized link and tooltip hover area
  src/SmartComponents/SubscriptionsUtilized/Constants.js
  src/SmartComponents/SubscriptionsUtilized/SubscriptionsUtilizedCard.js
  src/SmartComponents/SubscriptionsUtilized/SubscriptionsUtilizedCard.scss
Labels: enhancement

#142 make sure permissions exist before loading stuff
  src/App.js
Labels: bug
