Repository RedHatInsights/insights-dashboard, pull requests merged in 2020-06, with the labels that each got.

#156 Updates deps, includes FEC 2.0
  package-lock.json
  package.json
Labels: enhancement

#158 Update deps
  package-lock.json
  package.json
Labels: enhancement

#162 use per_page=1 for inventory to speed up calls
  src/AppConstants.js
Labels: enhancement

#159 update subscriptions utilized card, apply error code for opt-in
  src/SmartComponents/SubscriptionsUtilized/Constants.js
  src/SmartComponents/SubscriptionsUtilized/SubscriptionsUtilizedCard.js
Labels: enhancement

#163 Updates deps, makes compliance links accessible by pendo
  package-lock.json
  package.json
  src/SmartComponents/Compliance/ComplianceCard.js
  src/SmartComponents/Compliance/ComplianceCard.scss
Labels: enhancement

#164 RHICOMPL-708 - Fix Compliance wording and % compliant
  build/messages/src/Messages.json
  src/Messages.js
  src/SmartComponents/Compliance/ComplianceCard.js
Labels: bug

#165 Adds ids to stack chart and remediations run card in support of pendo
  src/ChartTemplates/StackChart/StackChartTemplate.js
  src/SmartComponents/Remediations/RemediationsCard.js
  src/SmartComponents/Remediations/RunStatus.js
Labels: :hammer_and_wrench: :waffle:, enhancement
