Repository RedHatInsights/insights-dashboard, pull requests merged in 2020-10, with the labels that each got.

#192 Reconfigures advisor card workload filter to now function correctly ✅🥰
  src/SmartComponents/Advisor/Advisor.js
Labels: :hammer_and_wrench: :waffle:, bug

#193 Update deps, fix undefined workload edge case
  package-lock.json
  package.json
  src/SmartComponents/Advisor/Advisor.js
Labels: :hammer_and_wrench: :waffle:, bug

#194 Show empty state for inventory card if user has no access to inv
  src/Messages.js
  src/SmartComponents/SystemInventory/SystemInventoryCard.js
  src/SmartComponents/SystemInventory/SystemInventoryCard.scss
Labels: :hammer_and_wrench: :waffle:, enhancement

#195 Cards that do not support workloads now indicate when they're selected 🤗
  build/messages/src/Messages.json
  locales/translations.json
  src/Messages.js
  src/SmartComponents/Advisor/Advisor.js
  src/SmartComponents/Compliance/ComplianceCard.js
  src/SmartComponents/SubscriptionsUtilized/SubscriptionsUtilizedCard.js
Labels: enhancement

#196 Pass sap_system and tags to inventory enpoints
  package-lock.json
  package.json
  src/SmartComponents/Advisor/Advisor.js
  src/SmartComponents/SystemInventory/SystemInventoryCard.js
  src/Utilities/Common.js
Labels: :hammer_and_wrench: :waffle:, enhancement

#197 Update deps and code cleanup🤗🏴‍☠️🦹‍♀️🥰
  .eslintrc.yml
  package-lock.json
  package.json
  src/ChartTemplates/PieChart/PieChartTemplate.js
  src/ChartTemplates/StackChart/StackChartTemplate.js
  src/SmartComponents/Advisor/Advisor.js
  src/SmartComponents/Compliance/ComplianceCard.js
  src/SmartComponents/PatchManager/PatchManagerCard.js
  src/SmartComponents/SystemInventory/SystemInventoryCard.js
Labels: :hammer_and_wrench: :waffle:, enhancement

#198 Hide Advisor TemplateCardHeader if advisorIncidentsStatus is rejected
  src/SmartComponents/Advisor/Advisor.js
Labels: :hammer_and_wrench: :waffle:, bug

#200 Use new global filter mapper format and pass SID filter to inv
  src/App.js
  src/AppActions.js
  src/AppConstants.js
  src/AppReducer.js
  src/SmartComponents/SystemInventory/SystemInventoryCard.js
Labels: enhancement

#199 Creates SAP zero state, temporarily hides inventory card rbac
  build/messages/src/Messages.json
  locales/translations.json
  src/AppConstants.js
  src/Messages.js
  src/PresentationalComponents/Dashboard/Dashboard.js
  src/PresentationalComponents/NoSystems/NoSystems.js
  src/PresentationalComponents/NoSystems/NoSystems.scss
  src/SmartComponents/SystemInventory/SystemInventoryCard.js
Labels: :hammer_and_wrench: :waffle:, On Hold, enhancement

#201 Patch card to support workloads/tagging/sids 🚤✅🥰
  src/App.js
  src/SmartComponents/Advisor/Advisor.js
  src/SmartComponents/PatchManager/PatchManagerCard.js
  src/SmartComponents/SystemInventory/SystemInventoryCard.js
  src/Utilities/Common.js
Labels: :hammer_and_wrench: :waffle:, enhancement

#202 Fix patch card tags query, add get param serializer 😀😃😄
  package-lock.json
  package.json
  src/SmartComponents/Advisor/Advisor.js
  src/SmartComponents/PatchManager/PatchManagerCard.js
  src/SmartComponents/SystemInventory/SystemInventoryCard.js
  src/Utilities/Api.js
Labels: :hammer_and_wrench: :waffle:, bug

#204 Update messaging on cards that don't support global filter
  build/messages/src/Messages.json
  locales/translations.json
  src/AppReducer.js
  src/Messages.js
  src/PresentationalComponents/FilterNotSupported.js
  src/PresentationalComponents/FilterNotSupported.scss
  src/SmartComponents/Compliance/ComplianceCard.js
  src/SmartComponents/SubscriptionsUtilized/SubscriptionsUtilizedCard.js
  src/SmartComponents/Vulnerability/VulnerabilityCard.js
  src/Utilities/Common.js
Labels: :hammer_and_wrench: :waffle:, enhancement

#203 Enable RBAC in inventory card, use new chrome API for global filter
  src/App.js
  src/SmartComponents/SystemInventory/SystemInventoryCard.js
  src/SmartComponents/SystemInventory/SystemInventoryCard.scss
Labels: enhancement

#205 Fix SID param for all da cards 😀😃😄😁, update deps
  package-lock.json
  package.json
  src/Utilities/Common.js
Labels: :hammer_and_wrench: :waffle:, bug
