Repository RedHatInsights/insights-dashboard, pull requests merged in 2020-05, with the labels that each got.

#143 Updates deps, cleans up build warnings
  package-lock.json
  package.json
  src/PresentationalComponents/NumberData/NumberData.js
  src/SmartComponents/Remediations/RunStatus.js
Labels: enhancement

#144 Adjusts stack chart color, tooltip position
  src/ChartTemplates/StackChart/StackChartTemplate.js
Labels: enhancement, needs design approval

#145 Fixes stack chart tooltip size, font, and position 👷‍♀️🥳🥺
  src/ChartTemplates/StackChart/StackChartTemplate.js
Labels: enhancement

#146 Update deps
  package-lock.json
  package.json
Labels: enhancement

#147 Refactors stack chart label to now have link underline
  src/ChartTemplates/StackChart/StackChartTemplate.js
Labels: bug

#149 Transition depreciated @red-hat-insights comopnent to @redhat-cloud-services, updates all non-breaking deps 🦹‍♀️🤗
  package-lock.json
  package.json
  src/App.scss
  src/PresentationalComponents/Dashboard/Dashboard.js
  src/PresentationalComponents/GaugeSection/GaugeSection.js
  src/PresentationalComponents/GaugeWidget/GaugeWidget.js
  src/PresentationalComponents/Loading/Loading.js
  src/PresentationalComponents/PageLoading/PageLoading.js
  src/PresentationalComponents/Skeleton/Skeleton.js
  src/PresentationalComponents/Skeleton/_Skeleton.scss
  src/SmartComponents/Remediations/RunStatus.js
  src/Utilities.scss
Labels: enhancement

#148 Fix accessibility issues
  build/messages/src/Messages.json
  locales/data.json
  locales/translations.json
  src/ChartTemplates/PieChart/PieChartTemplate.js
  src/ChartTemplates/PieChart/PieChartTemplate.scss
  src/ChartTemplates/StackChart/StackChartTemplate.js
  src/ChartTemplates/StackChart/_StackChartTemplate.scss
  src/Messages.js
  src/PresentationalComponents/IconInline/IconInline.js
  src/PresentationalComponents/NumberData/NumberData.scss
  src/PresentationalComponents/NumberDescription/NumberDescription.js
  src/PresentationalComponents/NumberDescription/NumberDescription.scss
  src/PresentationalComponents/Template/TemplateCard.js
  src/SmartComponents/Advisor/Advisor.js
  src/SmartComponents/PatchManager/PatchManagerCard.js
  src/SmartComponents/Vulnerability/VulnerabilityCard.js
Labels: bug

#151 Compliance: Fetch reports with results
  src/AppConstants.js
  src/SmartComponents/Compliance/ComplianceCard.js
Labels: bug

#152 Fix wrong operation to compute link to 'more policies'
  src/SmartComponents/Compliance/ComplianceCard.js
Labels: bug

#153 Add url redirect to stack chart, update deps and translations
  build/messages/src/Messages.json
  locales/data.json
  locales/translations.json
  package-lock.json
  package.json
  src/ChartTemplates/StackChart/StackChartTemplate.js
Labels: bug

#154 Fixes stackchart redirect 🤗💯👍🏽
  src/ChartTemplates/StackChart/StackChartTemplate.js
Labels: bug
