Repository RedHatInsights/insights-dashboard, pull requests merged in 2020-03, with the labels that each got.

#54 Adds Advisor Recommendations card
  build/messages/src/Messages.json
  locales/data.json
  locales/translations.json
  src/App.scss
  src/AppActions.js
  src/AppConstants.js
  src/AppReducer.js
  src/Messages.js
  src/PresentationalComponents/Dashboard/Dashboard.js
  src/SmartComponents/Advisor/Advisor.js
  src/SmartComponents/Advisor/Constants.js
  src/SmartComponents/Advisor/StackChart.js
Labels: enhancement

#58 Simplifies chart a lil bit, fixes urls
  src/SmartComponents/Advisor/Advisor.js
  src/SmartComponents/Advisor/StackChart.js
Labels: bug

#59 Updates advisor card as per mocks
  src/SmartComponents/Advisor/Advisor.js
  src/SmartComponents/Advisor/StackChart.js
  src/SmartComponents/Advisor/_Advisor.scss
Labels: enhancement

#60 Adds common capitalize function, advisor tooltips are now capitalized 🥰
  src/PresentationalComponents/GaugeWidget/GaugeWidget.js
  src/PresentationalComponents/Modal/ModalContent.js
  src/SmartComponents/Advisor/StackChart.js
  src/Utilities/Common.js
Labels: enhancement

#57 [WIP] Style chart
  build/messages/src/Messages.json
  locales/data.json
  locales/translations.json
  src/ChartTemplates/PieChart/PieChartTemplate.js
  src/ChartTemplates/PieChart/PieChartTemplate.scss
  src/ChartTemplates/StackChart/StackChartTemplate.js
  src/Messages.js
  src/PresentationalComponents/Dashboard/Dashboard.js
  src/PresentationalComponents/Dashboard/_dashboard.scss
  src/PresentationalComponents/NumberData/NumberData.scss
  src/PresentationalComponents/NumberDescription/NumberDescription.js
  src/PresentationalComponents/NumberDescription/NumberDescription.scss
  src/PresentationalComponents/Template/TemplateCard.js
  src/PresentationalComponents/Template/TemplateCard.scss
  src/SmartComponents/Advisor/Advisor.js
  src/SmartComponents/Compliance/ComplianceCard.js
  src/SmartComponents/OperatingSystems/OperatingSystemsCard.js
  src/SmartComponents/PatchManager/PatchManagerCard.js
  src/SmartComponents/Remediations/RemediationsCard.js
  src/SmartComponents/SubscriptionsUtilized/SubscriptionsUtilizedCard.js
  src/SmartComponents/SystemInventory/SystemInventoryCard.js
  src/SmartComponents/Vulnerability/VulnerabilityCard.js
Labels: enhancement

#61 Scope styles to cards, use PF vars when needed
  src/App.scss
  src/SmartComponents/Advisor/_Advisor.scss
Labels: bug

#67 Create pull_request_template.md
  .github/pull_request_template.md
Labels: docs, enhancement

#69 fix(compliance): update text and add links
  build/messages/src/Messages.json
  locales/data.json
  locales/translations.json
  src/Messages.js
  src/PresentationalComponents/Dashboard/_dashboard.scss
  src/SmartComponents/Compliance/ComplianceCard.js
Labels: enhancement

#70 add empty states for rbac
  .gitignore
  build/messages/src/Messages.json
  locales/data.json
  locales/translations.json
  src/App.js
  src/Messages.js
  src/PresentationalComponents/Dashboard/Dashboard.js
  src/PresentationalComponents/DeniedState/DeniedState.js
  src/PresentationalComponents/DeniedState/DeniedState.scss
  src/PresentationalComponents/PageLoading/PageLoading.js
  src/PresentationalComponents/PageLoading/PageLoading.scss
  src/Utilities/asyncComponent.js
Labels: enhancement

#71 Fill Patch dashboard card with the real data
  build/messages/src/Messages.json
  src/AppActions.js
  src/AppConstants.js
  src/AppReducer.js
  src/Messages.js
  src/SmartComponents/PatchManager/PatchManagerCard.js
  src/SmartComponents/PatchManager/PatchManagerCard.scss
Labels: enhancement

#72 fix pie chart styles
  src/ChartTemplates/PieChart/PieChartTemplate.js
  src/ChartTemplates/PieChart/PieChartTemplate.scss
  src/SmartComponents/Compliance/ComplianceCard.js
  src/SmartComponents/PatchManager/PatchManagerCard.js
Labels: bug

#68 Update stack chart template (remove stack chart from advisor)
  locales/data.json
  locales/translations.json
  src/ChartTemplates/StackChart/StackChartTemplate.js
  src/PresentationalComponents/NumberDescription/NumberDescription.js
  src/SmartComponents/Advisor/Advisor.js
  src/SmartComponents/Advisor/StackChart.js
  src/SmartComponents/Vulnerability/VulnerabilityCard.js
Labels: enhancement

#75 Corrects stack chart alignment, advisor card cleanup
  src/ChartTemplates/StackChart/StackChartTemplate.js
  src/ChartTemplates/StackChart/_StackChartTemplate.scss
  src/SmartComponents/Advisor/Advisor.js
  src/SmartComponents/Advisor/_Advisor.scss
Labels: bug

#65 Populate data for Vulnerability card
  locales/data.json
  locales/translations.json
  src/AppActions.js
  src/AppConstants.js
  src/AppReducer.js
  src/Messages.js
  src/SmartComponents/Vulnerability/VulnerabilityCard.js
Labels: enhancement

#74 Scope button styles and fix empty state
  build/messages/src/Messages.json
  locales/data.json
  locales/translations.json
  src/Messages.js
  src/PresentationalComponents/Dashboard/_dashboard.scss
  src/PresentationalComponents/DownloadReport/DownloadReport.js
  src/PresentationalComponents/DownloadReport/DownloadReport.scss
  src/SmartComponents/Compliance/ComplianceCard.js
Labels: bug

#81 Compliance - Nests pie charts and "more.." text in parent
  build/messages/src/Messages.json
  src/SmartComponents/Compliance/ComplianceCard.js
Labels: bug

#83 Update ui-base because it changed
  src/AppConstants.js
Labels: bug

#82 WIP Populate data for Subscriptions Utilized card
  build/messages/src/Messages.json
  locales/data.json
  locales/translations.json
  src/AppActions.js
  src/AppConstants.js
  src/AppReducer.js
  src/ChartTemplates/Progress/ProgressTemplate.js
  src/Messages.js
  src/SmartComponents/SubscriptionsUtilized/Constants.js
  src/SmartComponents/SubscriptionsUtilized/SubscriptionsUtilizedCard.js
  src/SmartComponents/SubscriptionsUtilized/SubscriptionsUtilizedHelpers.js
Labels: enhancement

#90 update travis yml to remove after_success
  .travis.yml
  package-lock.json
Labels: bug, enhancement
