Repository RedHatInsights/insights-dashboard, pull requests merged in 2020-12, with the labels that each got.

#212 fix(compliance): RHICOMPL-1181 Group results by policy
  src/AppConstants.js
  src/SmartComponents/Compliance/ComplianceCard.js
Labels: :hammer_and_wrench: :waffle:, bug

#213 fix(compliance): RHICOMPL-1181 Group results by policy
  src/AppConstants.js
  src/SmartComponents/Compliance/ComplianceCard.js
Labels: On Hold, bug

#214 Update deps 🙇🏽⏱🦾
  package-lock.json
  package.json
Labels: :hammer_and_wrench: :waffle:

#215 Update deps again! 🤪🦎📢
  package-lock.json
  package.json
Labels: :hammer_and_wrench: :waffle:
