Repository RedHatInsights/insights-dashboard, pull requests merged in 2020-08, with the labels that each got.

#172 Add Tooltip for longer remediation names
  src/SmartComponents/Remediations/RunStatus.js
Labels: bug

#173 Update deps cuz its been a minute 🤙🏾
  package-lock.json
  package.json
Labels: :hammer_and_wrench: :waffle:, enhancement

#174 Activate RBAC permissions for Subscription Watch
  src/App.js
Labels: :hammer_and_wrench: :waffle:, enhancement

#175 Add link to Registration app on no systems page
  build/messages/src/Messages.json
  locales/data.json
  locales/translations.json
  src/Messages.js
  src/PresentationalComponents/NoSystems/NoSystems.js
Labels: enhancement

#176 Compliance button urls redirect correctly on beta
  src/SmartComponents/Compliance/ComplianceCard.js
Labels: bug

#177 fix(Patch PieChart): pie chart legend color mistmatch
  src/SmartComponents/PatchManager/PatchManagerCard.js
Labels: bug

#179 Reduce intl logging by trimming locals
  src/entry-dev.js
  src/entry.js
Labels: :hammer_and_wrench: :waffle:, bug

#180 Update deps 🥰💪
  package-lock.json
  package.json
  sitemap.xml
Labels: :hammer_and_wrench: :waffle:, enhancement
