Repository RedHatInsights/insights-dashboard, pull requests merged in 2020-07, with the labels that each got.

#157 Changes required for Dashboard to support pf4 updates
  package-lock.json
  package.json
  src/PresentationalComponents/GaugeWidget/GaugeWidget.js
  src/PresentationalComponents/NoSystems/NoSystems.js
  src/PresentationalComponents/NumberDescription/NumberDescription.js
  src/PresentationalComponents/Template/TemplateCard.js
  src/SmartComponents/Compliance/ComplianceCard.js
  src/SmartComponents/Remediations/RemediationsCard.js
  src/SmartComponents/Remediations/RemediationsCard.scss
Labels: enhancement

#166 Update the deps!
  package-lock.json
  package.json
Labels: :hammer_and_wrench: :waffle:, enhancement

#167 Fix sys-inv card tooltip, also fix text spacing
  package-lock.json
  package.json
  src/PresentationalComponents/NumberData/NumberData.js
  src/PresentationalComponents/NumberData/NumberData.scss
  src/PresentationalComponents/NumberDescription/NumberDescription.js
  src/PresentationalComponents/NumberDescription/NumberDescription.scss
  src/SmartComponents/SystemInventory/SystemInventoryCard.js
  src/SmartComponents/SystemInventory/SystemInventoryCard.scss
  src/SmartComponents/Vulnerability/VulnerabilityCard.js
Labels: bug

#168 Update StackChart width for Vuln and Advisor
  src/SmartComponents/Advisor/Advisor.js
  src/SmartComponents/Vulnerability/VulnerabilityCard.js
Labels: bug

#170 Update deps, gotta add typescript as peer
  package-lock.json
  package.json
Labels: enhancement

#171 Patch - fetch the minimal set of data as we read only meta section
  src/AppConstants.js
Labels: bug

#169 Fix StackChart Tooltip size
  src/ChartTemplates/StackChart/StackChartTemplate.js
  src/ChartTemplates/StackChart/_StackChartTemplate.scss
  src/SmartComponents/Advisor/Advisor.js
  src/SmartComponents/Vulnerability/VulnerabilityCard.js
Labels: bug
