Repository RedHatInsights/insights-dashboard, pull requests merged in 2021-07, with the labels that each got.

#257 Update deps 🪂🥸🥳
  package-lock.json
  package.json
Labels: dependencies

#258 Update URL parameters on vulnerability card
  src/SmartComponents/Vulnerability/VulnerabilityCard.js
Labels: bug

#259 Update deps, fix tooltip text 🥳🫐
  build/messages/src/Messages.json
  locales/translations.json
  package-lock.json
  package.json
  src/Messages.js
  src/PresentationalComponents/Template/DataListItemTemplate.scss
  src/SmartComponents/Advisor/Advisor.js
Labels: enhancement
