Repository RedHatInsights/insights-dashboard, pull requests merged in 2021-01, with the labels that each got.

#217 Update deps 🥳🥳🥳
  package-lock.json
  package.json
Labels: dependencies

#218 Remove Red Hat from insights
  build/messages/src/Messages.json
  locales/translations.json
  src/Messages.js
  src/index.html
Labels: :hammer_and_wrench: :waffle:

#220 Chrome 2.Oh upgrade! Also deps 🥰🤷‍♀️
  config/dev.webpack.config.js
  config/prod.webpack.config.js
  package-lock.json
  package.json
  src/AppEntry.js
  src/Routes.js
  src/bootstrap-dev.js
  src/bootstrap.js
  src/entry-dev.js
  src/entry.js
Labels: enhancement

#219 VULN-1471 Enable global filter for Vulnerability card
  package-lock.json
  package.json
  src/AppConstants.js
  src/SmartComponents/Vulnerability/VulnerabilityCard.js
Labels: On Hold, enhancement

#222 Update deps, FEC v2 👉v3 📸
  .eslintignore
  .eslintrc.yml
  config/dev.webpack.config.js
  config/prod.webpack.config.js
  config/test.webpack.config.js
  package-lock.json
  package.json
  src/App.scss
  src/AppEntry.js
  src/PresentationalComponents/Dashboard/Dashboard.js
  src/PresentationalComponents/Loading/Loading.js
  src/PresentationalComponents/NoSystems/NoSystems.js
  src/PresentationalComponents/Skeleton/Skeleton.js
  src/PresentationalComponents/Skeleton/_Skeleton.scss
  src/SmartComponents/Advisor/Advisor.js
  src/SmartComponents/Compliance/ComplianceCard.js
  src/SmartComponents/Remediations/RemediationsCard.js
  src/SmartComponents/SystemInventory/SystemInventoryCard.js
  src/Store/index.js
  src/Utilities.scss
  src/Utilities/Common.js
  src/entry.test.js
Labels: :hammer_and_wrench: :waffle:, dependencies

#223 Speed up build
  .babelrc
  babel.config.js
  config/prod.webpack.config.js
  package-lock.json
  package.json
  src/ChartTemplates/StackChart/StackChartTemplate.js
  src/SmartComponents/Advisor/Advisor.js
  src/SmartComponents/Compliance/ComplianceCard.js
  src/SmartComponents/PatchManager/PatchManagerCard.js
Labels: enhancement
