Repository RedHatInsights/insights-dashboard, pull requests merged in 2021-04, with the labels that each got.

#239 feat(dashboard): updated css
  build/messages/src/Messages.json
  locales/translations.json
  src/App.scss
  src/ChartTemplates/PieChart/PieChartTemplate.js
  src/ChartTemplates/Progress/ProgressTemplate.js
  src/ChartTemplates/StackChart/StackChartTemplate.js
  src/Icons/CriticalIcon.js
  src/Icons/FinishedIcon.js
  src/Icons/InfoIcon.js
  src/Icons/QuestionIcon.js
  src/Icons/RunningIcon.js
  src/Icons/WarningIcon.js
  src/Messages.js
  src/PresentationalComponents/Dashboard/Dashboard.js
  src/PresentationalComponents/Dashboard/dashboard.scss
  src/PresentationalComponents/DashboardIcon/DashboardIcon.js
  src/PresentationalComponents/DashboardIcon/DashboardIcon.scss
  src/PresentationalComponents/DeniedState/DeniedState.js
  src/PresentationalComponents/DownloadReport/DownloadReport.js
  src/PresentationalComponents/FailState/FailState.js
  src/PresentationalComponents/FilterNotSupported.js
  src/PresentationalComponents/IconInline/IconInline.js
  src/PresentationalComponents/MarketingBanner/MarketingBanner.js
  src/PresentationalComponents/NoSystems/NoSystems.js
  src/PresentationalComponents/NumberData/NumberData.js
  src/PresentationalComponents/NumberDescription/NumberDescription.js
  src/PresentationalComponents/PageLoading/PageLoading.js
  src/PresentationalComponents/Skeleton/Skeleton.js
  src/PresentationalComponents/Template/AppBlockTemplate.js
  src/PresentationalComponents/Template/CompoundCard.js
  src/PresentationalComponents/Template/CompoundCard.scss
  src/PresentationalComponents/Template/DataListItemTemplate.js
  src/PresentationalComponents/Template/ExpandableCardTemplate.js
  src/PresentationalComponents/Template/TemplateCard.js
  src/PresentationalComponents/VerticalDivider/VerticalDivider.js
  src/SmartComponents/Advisor/Advisor.js
  src/SmartComponents/CustomPolicies/CustomPoliciesCard.js
  src/SmartComponents/Footer/Footer.js
  src/SmartComponents/NewRules/NewRules.js
  src/SmartComponents/NewRules/NewRules.scss
  src/SmartComponents/PatchManager/PatchManagerCard.js
  src/SmartComponents/Policies/PoliciesCard.js
  src/SmartComponents/Remediations/RemediationsCard.js
  src/SmartComponents/Remediations/RemediationsEmptyState.js
  src/SmartComponents/Remediations/RunStatus.js
  src/SmartComponents/SubscriptionsUtilized/SubscriptionsUtilizedCard.js
  src/SmartComponents/SystemInventory/SystemInventoryCard.js
  src/SmartComponents/SystemInventory/SystemInventoryHeader.js
  src/SmartComponents/Vulnerability/VulnerabilityCard.js
  src/SmartComponents/Vulnerability/VulnerabilityCard.scss
  src/Utilities/Common.js
Labels: :hammer_and_wrench: :waffle:, enhancement

#240 provide breakdown of known exploits by CVSS on vuln card
  src/SmartComponents/Vulnerability/VulnerabilityCard.js
Labels: :hammer_and_wrench: :waffle:, enhancement

#241 Simplify vuln chart legend
  src/SmartComponents/Vulnerability/VulnerabilityCard.js
Labels: enhancement

#242 Update deps 🥑🥑🥳🥳💯🥸also, if we have no newrule node_id hide the kba link
  package-lock.json
  package.json
  src/SmartComponents/NewRules/NewRules.js
Labels: :hammer_and_wrench: :waffle:, dependencies

#243 vulnerability: use correct fields for the data
  src/SmartComponents/Vulnerability/VulnerabilityCard.js
Labels: enhancement

#244 Adds exploited tooltip to vuln card
  build/messages/src/Messages.json
  locales/translations.json
  src/Messages.js
  src/SmartComponents/Remediations/RunStatus.js
  src/SmartComponents/Remediations/RunStatus.scss
  src/SmartComponents/Vulnerability/VulnerabilityCard.js
Labels: :hammer_and_wrench: :waffle:, enhancement

#245 swatch: Update links
  src/SmartComponents/SubscriptionsUtilized/Constants.js
Labels: bug

#246 Respect beta path on Patch card
  src/SmartComponents/PatchManager/PatchManagerCard.js
Labels: bug

#247 Respect beta path on Subscriptions card
  src/AppConstants.js
  src/SmartComponents/SubscriptionsUtilized/Constants.js
Labels: bug

#249 Update deps 🥑🥳🤙🏾
  package-lock.json
  package.json
Labels: dependencies

#248 fix(dashboard): unbroke mobile layout
  src/App.scss
  src/Messages.js
  src/PresentationalComponents/Dashboard/dashboard.scss
  src/PresentationalComponents/Template/DataListItemTemplate.js
  src/PresentationalComponents/Template/DataListItemTemplate.scss
  src/SmartComponents/Advisor/Advisor.js
  src/SmartComponents/CustomPolicies/CustomPoliciesCard.scss
  src/SmartComponents/NewRules/NewRules.scss
  src/SmartComponents/PatchManager/PatchManagerCard.js
  src/SmartComponents/SystemInventory/SystemInventoryHeader.js
  src/SmartComponents/SystemInventory/SystemInventoryHeader.scss
  src/SmartComponents/Vulnerability/VulnerabilityCard.js
  src/SmartComponents/Vulnerability/VulnerabilityCard.scss
Labels: bug
