Repository RedHatInsights/insights-dashboard, pull requests merged in 2021-03, with the labels that each got.

#229 Update da deps 💍🦷🫀
  package-lock.json
  package.json
Labels: dependencies

#230 refactor(dashboard): refactored dashboard
  build/messages/src/Messages.json
  locales/data.json
  locales/translations.json
  src/App.scss
  src/AppConstants.js
  src/Messages.js
  src/PresentationalComponents/Dashboard/Dashboard.js
  src/PresentationalComponents/Dashboard/_dashboard.scss
  src/PresentationalComponents/NumberData/NumberData.js
  src/PresentationalComponents/NumberDescription/NumberDescription.js
  src/PresentationalComponents/Template/AppBlockTemplate.js
  src/PresentationalComponents/Template/AppBlockTemplate.scss
  src/PresentationalComponents/Template/DataListItemTemplate.js
  src/PresentationalComponents/Template/DataListItemTemplate.scss
  src/PresentationalComponents/Template/ExpandableCardTemplate.js
  src/PresentationalComponents/Template/TemplateCard.js
  src/PresentationalComponents/Template/TemplateCard.scss
  src/SmartComponents/Advisor/Advisor.js
  src/SmartComponents/Advisor/Constants.js
  src/SmartComponents/Compliance/ComplianceCard.js
  src/SmartComponents/Compliance/ComplianceCard.scss
  src/SmartComponents/Footer/Footer.js
  src/SmartComponents/NewRules/NewRules.js
  src/SmartComponents/NewRules/NewRules.scss
  src/SmartComponents/PatchManager/PatchManagerCard.js
  src/SmartComponents/PatchManager/PatchManagerCard.scss
  src/SmartComponents/Policies/PoliciesCard.js
  src/SmartComponents/Remediations/RemediationsCard.js
  src/SmartComponents/Remediations/RemediationsEmptyState.js
  src/SmartComponents/SubscriptionsUtilized/SubscriptionsUtilizedCard.js
  src/SmartComponents/SystemInventory/SystemInventoryHeader.js
  src/SmartComponents/Vulnerability/VulnerabilityCard.js
Labels: :hammer_and_wrench: :waffle:, enhancement

#232 added masonry layout
  package-lock.json
  package.json
  src/App.scss
  src/AppEntry.js
  src/PresentationalComponents/Dashboard/Dashboard.js
  src/PresentationalComponents/Dashboard/_dashboard.scss
  src/PresentationalComponents/NumberData/NumberData.scss
  src/PresentationalComponents/Template/DataListItemTemplate.js
  src/PresentationalComponents/Template/DataListItemTemplate.scss
  src/PresentationalComponents/Template/ExpandableCardTemplate.js
  src/PresentationalComponents/Template/TemplateCard.js
  src/PresentationalComponents/Template/TemplateCard.scss
  src/SmartComponents/Advisor/Advisor.js
  src/SmartComponents/Advisor/Constants.js
  src/SmartComponents/Footer/Footer.js
  src/SmartComponents/NewRules/NewRules.js
  src/SmartComponents/NewRules/NewRules.scss
  src/SmartComponents/SystemInventory/SystemInventoryHeader.js
  src/SmartComponents/SystemInventory/SystemInventoryHeader.scss
  src/SmartComponents/Vulnerability/VulnerabilityCard.js
  src/Utilities/Common.js
Labels: :hammer_and_wrench: :waffle:, bug

#233 Followup to #232, new rule hiding, footer cards, other refactoring 🧑‍🎤🤙🏾
  build/messages/src/Messages.json
  locales/translations.json
  src/App.js
  src/Messages.js
  src/PresentationalComponents/Dashboard/Dashboard.js
  src/PresentationalComponents/Template/DataListItemTemplate.js
  src/PresentationalComponents/Template/DataListItemTemplate.scss
  src/Routes.js
  src/SmartComponents/Advisor/Advisor.js
  src/SmartComponents/Footer/Footer.js
  src/SmartComponents/NewRules/NewRules.js
  src/SmartComponents/Vulnerability/VulnerabilityCard.js
  src/images/Icon-Red_Hat-Software_and_Technologies-Automation-A-Red-RGB.svg
  src/images/Icon-Red_Hat-Software_and_technologies-App_Secured-A-Red-RGB.svg
Labels: :hammer_and_wrench: :waffle:, enhancement

#234 use correct link to vulnerability application
  src/SmartComponents/Vulnerability/VulnerabilityCard.js
Labels: enhancement

#235 Adds start:proxy, running the frontend without proxy terminal 🤯🥑💌
  README.md
  config/dev.webpack.config.js
  package.json
Labels: :hammer_and_wrench: :waffle:, enhancement

#236 Hide unregistered, unifies patch/subwatch title, persist card expanded 🤯
  src/PresentationalComponents/Template/ExpandableCardTemplate.js
  src/SmartComponents/Advisor/Advisor.js
  src/SmartComponents/Advisor/Advisor.scss
  src/SmartComponents/Compliance/ComplianceCard.js
  src/SmartComponents/NewRules/NewRules.js
  src/SmartComponents/PatchManager/PatchManagerCard.js
  src/SmartComponents/Remediations/RemediationsCard.js
  src/SmartComponents/SubscriptionsUtilized/SubscriptionsUtilizedCard.js
  src/SmartComponents/SystemInventory/SystemInventoryHeader.js
  src/SmartComponents/Vulnerability/VulnerabilityCard.js
Labels: :hammer_and_wrench: :waffle:, enhancement

#237 Update deps 🤙🏾💌☕️😌👩‍🏫🫀 (#805)
  package-lock.json
  package.json
Labels: :hammer_and_wrench: :waffle:, dependencies

#238 Vuln card url switcheroo 👘💍
  src/SmartComponents/Vulnerability/VulnerabilityCard.js
Labels: enhancement
