Repository RedHatInsights/insights-dashboard, pull requests merged in 2021-05, with the labels that each got.

#250 Fix security url, removes insights base
  src/PresentationalComponents/ZeroState/ZeroState.js
Labels: bug

#251 Update deps 🦑🤠❤️‍🔥
  .stylelint.json
  .stylelintrc.json
  package-lock.json
  package.json
  src/App.scss
  static/images/rh-logo-white.svg
Labels: dependencies

#252 add ability to use beta
  config/dev.webpack.config.js
  package.json
Labels: enhancement

#253 Increases dashboard max-width as per ux rec 🍷㉿
  src/PresentationalComponents/Dashboard/dashboard.scss
Labels: :hammer_and_wrench: :waffle:
