Repository RedHatInsights/insights-dashboard, pull requests merged in 2021-02, with the labels that each got.

#224 Rename custom Dashboard webpack chunk name.
  src/Routes.js
Labels: bug

#225 Use fec charts and translations packages to v3.
  package-lock.json
  package.json
  src/AppEntry.js
Labels: dependencies

#226 Update deps 👩‍🏫🍔✂️
  package-lock.json
  package.json
Labels: dependencies

#227 Accommodate removal of "all workloads" workload 🐚
  src/Utilities/Common.js
Labels: bug

#228 Update deps 👩‍🏫🍔😇
  package-lock.json
  package.json
Labels: :hammer_and_wrench: :waffle:, dependencies

#221 Vulnerability: Use cvss_from and cvss_to params instead of cvss_filter
  src/SmartComponents/Vulnerability/Constants.js
  src/SmartComponents/Vulnerability/VulnerabilityCard.js
Labels: On Hold, enhancement
